feat(UIKIT-912): Реализована основа приложения
kaluga-astral/technology-radar pull request #1
Opened 2023-09-07 13:18 UTC by Bblchock

2023-09-07 13:33 UTC, AndTem requested changes

2023-09-07 13:33 UTC, AndTem commented on index.html
> +    <title>Vite + React + TS</title>
Тех. радар Астрал-Софт

2023-09-07 13:33 UTC, AndTem commented on index.html
> +    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
возьми астраловскую иконку

2023-09-07 13:33 UTC, AndTem commented on src/constants/index.ts
> +export const drawerWidth = 150;
зачем?

2023-09-07 13:33 UTC, AndTem commented on src/icons/index.ts
> +export { ChevronLeft, Menu } from '@mui/icons-material';
icons === components. там и должен лежать

2023-09-07 13:33 UTC, AndTem commented on src/index.css
> +:root {
зачем это все?

2023-09-07 13:33 UTC, AndTem commented on src/pages/Header/Header.tsx
> +    <Toolbar sx={{ backgroundColor: '#f1f1f1' }}>
https://track.astral.ru/soft/wiki/pages/viewpage.action?pageId=3813157777

2023-09-07 13:33 UTC, AndTem commented on src/pages/Header/Header.tsx
> +export const Header = ({ open, onClick }: HeaderPropsType) => (
pages в components перетащи

2023-09-07 13:33 UTC, AndTem commented on src/pages/Header/types.ts
> +export type HeaderPropsType = { open: boolean; onClick: () => void };
Это не по style guide

2023-09-07 13:33 UTC, AndTem commented on src/pages/SideBarLeft/types.ts
> +export type SideBarLeftPropsType = {
Зачем type постфикс?
И по style guide пропсы в компоненте должны быть

2023-09-07 13:33 UTC, AndTem commented on src/App.tsx
> +                key={'route-' + rootApp}
https://track.astral.ru/soft/wiki/pages/viewpage.action?pageId=3557425260#id-%D0%9F%D1%80%D0%B8%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5%D1%82%D0%B8%D0%BF%D0%BE%D0%B2-%D0%94%D0%BB%D1%8F%D1%81%D0%BA%D0%BB%D0%B5%D0%B8%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F%D1%81%D1%82%D1%80%D0%BE%D0%BA%D0%BD%D0%B5%D0%BE%D0%B1%D1%85%D0%BE%D0%B4%D0%B8%D0%BC%D0%BE%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D1%8C%D1%81%D1%82%D1%80%D0%BE%D0%BA%D0%BE%D0%B2%D1%8B%D0%B9%D1%88%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD

2023-09-07 13:33 UTC, AndTem commented on src/App.tsx
> +              element={<Button variant="contained">Не найдено</Button>}
Зачем button?

2023-09-07 13:33 UTC, AndTem commented on src/config/edo.ts
> +export const sidebarItem: string = 'ЭДО';
config не должен ничего знать о sidebar

2023-09-07 13:33 UTC, AndTem commented on src/config/edo.ts
> +type Radar = {
В каждом файле один и тот же тип. Он должен быть общий и называть Config

2023-09-07 13:33 UTC, AndTem commented on src/config/edo.ts
> +export const rootApp: string = 'edo';
Очень сложно все.
Сделай просто объект, где будут:
productName
productId
radarData

2023-09-07 13:33 UTC, AndTem commented on src/utils/getDataConfig/types.ts
> +export type DataType = {
types лежит в utils и используется не только внутри утилы.
Если тип ипользуется вне утилы, то он явно должен быть не в utils

2023-09-07 13:33 UTC, AndTem commented on src/utils/getDataConfig/getDataConfig.ts
> +  return Object.values(CONFIG).map(({ rootApp, sidebarItem }) => {
А если возьмешь keys, то получишь названия продуктов, которые можно подставлять в route. При условии, что один файл конфига будет содержать один объект

2023-09-08 09:43 UTC, Bblchock commented on src/constants/index.ts
> +export const drawerWidth = 150;
чтобы двигать бургер, хедер и мейн при открытии менюшки

2023-09-11 08:02 UTC, AndTem requested changes

2023-09-11 08:02 UTC, AndTem commented on src/config/types.ts
> +export type ProductConfigType = {
Постфикс type не нужен

2023-09-11 08:02 UTC, AndTem commented on src/utils/getDataConfig/getDataConfig.ts
> +import { AllConfigsDataType } from '../../config/types';
Все импорты должны происходить через index файл:
'../../config'

2023-09-11 08:02 UTC, AndTem commented on src/config/edo.ts
> +  productId: 1,
Название переменной и есть id продукта

2023-09-11 08:02 UTC, AndTem commented on src/components/SideBarLeft/SideBarLeft.tsx
> +    <SideBar variant="persistent" anchor="left" open={isDrawerShow}>
Тебе не нужен SideBarLeft.
Просто сделать Sidebar компонент, в котором лежит styles со стилизацией контейнера

2023-09-11 08:02 UTC, AndTem commented on src/components/SideBarLeft/SideBarLeft.tsx
> +  listItems: AllConfigsDataType;
Название ни о чем не говорящее. 
Подойдет: products

2023-09-11 08:02 UTC, AndTem commented on src/components/Header/Header.tsx
> +      <Hamburger
Не понятно почему ты Toolbar вложил в header, а AppBar, Hamburger не вложил

2023-09-11 08:03 UTC, AndTem commented on src/constants/index.ts
> +export const drawerWidth = 150;
Не надо его двигать. Пусть поверх открывается

2023-09-14 10:54 UTC, AndTem requested changes

2023-09-14 10:54 UTC, AndTem commented on src/components/MenuItem/MenuItem.ts
> +  height: theme.spacing(8),
Высота заданы через отступы.
Даже семантически выглядит неправильно

2023-09-14 10:54 UTC, AndTem commented on src/App.tsx
> +  const handleDrawerClose = (): void => {
у тебя точно eslint работает?
Он должен добавить отступы между функциями

2023-09-14 10:55 UTC, AndTem commented on src/config/edo.ts
> +  productId: 1,
Это значит, что в getDataConfigs ты можешь подставить в productId название объекта.
И будешь работать в приложении уже с объектом, а не массивов [ключ,значение]

2023-09-14 10:58 UTC, AndTem commented on src/components/SideBar/SideBar.tsx
> +    <DrawerStyled variant="persistent" anchor="left" open={isDrawerShow}>
Используй temporary variant, чтобы радар не кривило

2023-10-05 10:08 UTC, AndTem approved these changes

2023-10-05 10:08 UTC, merged