feat: Тех радар для Web-Регистратора
kaluga-astral/technology-radar pull request #7
Opened 2024-08-07 14:49 UTC by Bblchock

2024-08-08 07:27 UTC, AndTem requested changes

2024-08-08 07:27 UTC, AndTem commented on public/kedo.json
> -  {
Почему в КЭДО удалил?

2024-08-08 07:27 UTC, AndTem commented on public/wr.json
> +    "ring": "adopt",
А не trial?

2024-08-08 07:27 UTC, AndTem commented on public/wr.json
> +    "ring": "adopt",
ПОхоже на trial сечас

2024-08-08 07:27 UTC, AndTem commented on public/wr.json
> +    "name": "core-js",
Уверен? Он внутри babel всегда используется. Да и указывать его не имеет смысла

2024-08-08 07:27 UTC, AndTem commented on public/wr.json
> +    "name": "react-router-dom",
укажи версию: react-router-dom@5

2024-08-08 07:27 UTC, AndTem commented on public/wr.json
> +    "description": "Не используется"
Что это значит? Не будет использовать или вообще не используется/

2024-08-08 07:27 UTC, AndTem commented on public/wr.json
> +    "ring": "adopt",
Не trial?

2024-08-08 07:27 UTC, AndTem commented on public/common.json
> +    "name": "core-js",
удали от сюда

2024-08-08 07:27 UTC, AndTem commented on public/common.json
> +    "description": "Постепенно перевозим реализованный функционал в пользу новой архитектуры и mobx"
Этот комментарий не относится к common.
Скорее надо: Используется в КЭДО

2024-08-08 07:27 UTC, AndTem commented on public/common.json
> +    "ring": "hold",
А у ОФД adopt

2024-08-08 07:28 UTC, Bblchock commented on public/kedo.json
> -  {
а это дубль, там выше то же самое. В коммите указал, что это дубль

2024-08-08 07:29 UTC, Bblchock commented on public/wr.json
> +    "ring": "adopt",
ну не знаю, он полгода уже у нас, только не везде)

2024-08-08 08:16 UTC, Bblchock commented on public/wr.json
> +    "ring": "adopt",
оставим adopt, т.к. уже более полугода работает

2024-08-08 08:16 UTC, Bblchock commented on public/wr.json
> +    "ring": "adopt",
оставим adopt, т.к. уже более полугода используется

2024-08-08 08:25 UTC, Bblchock commented on public/wr.json
> +    "description": "Не используется"
Не используется и не будет использоваться.
Удалю тогда лучше

2024-08-09 11:03 UTC, AndTem approved these changes

2024-08-09 11:05 UTC, merged